version: "3"

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    # networks:
    #   - fcexperience

  db:
    image: mysql:8
    container_name: mysql_web
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat
      MYSQL_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
    # networks:
    #   - fcexperience

# networks:
#   fcexperience:
#     external: true
